### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by okonon** [philmerrell/CanOpen#1]
I really like your plugin!
Are there any plans to support Android?

**Comment by philbot5000** [comment]
That's great to hear. Thanks!

Opening native apps in Android works a little different.  I've had the most luck on Android by using the InAppBrowser plugin passing in `_system` in as the 'target' parameter.

`var ref = window.open('https://twitter.com/philmerrell', '_system', 'location=yes');`

The `_system` (as opposed to `_blank` and `_self`) option is not very well documented, but it seems to pass the url to Android where it's evaluated which apps (beside the web browser) can open the link.

As far as I understand, Android apps can establish "Intents" that allow native apps to handle content from a URI.

Try using the `InAppBrowser` method for Android and if you like, let me know how it works for you.  If there seems like a definite need for a plugin, I'll look a little closer.

**Comment by hugo4le** [comment]
I also really like and appreciate your idea about this plugin. 
Since I just start using phonegap , can you show a sample of how to install your plugin in my android app?
